[package]
name = "wordsearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.34.0"
petgraph = "0.6.0"
regex = "1.5.5"
rand = {version="0.8.5", features=["small_rng"]}